---
abstract: 'Framework for implementing Git (and Gerrit) hooks'
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  Cwd: 0
  File::pushd: 0
  Test::More: 0
  URI::file: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Hooks
recommends:
  JIRA::REST: 0
  Text::SpellChecker: 0
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Data::Util: 0
  Encode: 0
  Error: 0
  Exporter: 0
  File::Path: 0
  File::Spec::Functions: 0
  Gerrit::REST: 0
  Git: 0
  List::MoreUtils: 0
  Path::Tiny: 0
  Text::Glob: 0
  parent: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  homepage: https://metacpan.org/module/Git::Hooks
  repository: https://github.com/gnustavo/Git-Hooks.git
version: 1.6.0
