---
abstract: 'A framework for implementing Git hooks.'
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  Config: 0
  Cwd: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  File::Temp: 0
  Test::More: 0
  URI::file: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Hooks
requires:
  App::gh::Git: 0
  Carp: 0
  Data::Util: 0
  Error: 0
  Exporter: 0
  File::Basename: 0
  File::Spec::Functions: 0
  JIRA::Client: 0
  List::MoreUtils: 0
  parent: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: https://metacpan.org/module/Git::Hooks
  repository: https://github.com/gnustavo/Git-Hooks.git
version: 0.015
